top_view_zoom_factor: 0.9
top_view_pan: '0,0,0'
bottom_view_zoom_factor: 0.9
bottom_view_pan: '0,0,0'
side_view_zoom_factor: 0.8
side_view_rotate: '315,360,405'
side_view_pan: '0,0,0'
left_view_zoom_factor: 1
left_view_pan: '0,0,0'
right_view_zoom_factor: 1
right_view_pan: '0,0,0'